"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from environs import Env

from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy

env = Env()
env.read_env()

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-t*0%lt0bc(01@a3#l+es^2byp+(vv^db2q&@-mr_zv5c0&a0cu'

DEBUG = True

ALLOWED_HOSTS = ['*']


INSTALLED_APPS = [
    'corsheaders',
    'unfold',
    'unfold.contrib.filters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'paytechuz.integrations.django',

    'apps.authentication',

    'apps.payment',

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

AUTH_USER_MODEL = 'authentication.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

UNFOLD = {
    "SITE_TITLE": "PayTechUZ Admin",
    "SITE_HEADER": "PayTechUZ Admin",
    "SITE_URL": "/",
    # "SITE_ICON": {
    #     "light": lambda request: static("icon.svg"),  # light mode
    #     "dark": lambda request: static("icon-dark.svg"),  # dark mode
    # },
    # "SITE_LOGO": {
    #     "light": lambda request: static("logo.svg"),  # light mode
    #     "dark": lambda request: static("logo-dark.svg"),  # dark mode
    # },
    "COLORS": {
        "primary": {
            "50": "239 246 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "59 130 246",
            "600": "37 99 235",
            "700": "29 78 216",
            "800": "30 64 175",
            "900": "30 58 138",
            "950": "23 37 84",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Users"),
                "separator": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "people",
                        "link": reverse_lazy("admin:authentication_user_changelist"),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "groups",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
            {
                "title": _("Payments"),
                "separator": True,
                "items": [
                    {
                        "title": _("Wallets"),
                        "icon": "account_balance_wallet",
                        "link": reverse_lazy("admin:payment_wallet_changelist"),
                    },
                ],
            },
        ],
    },
}


PAYTECHUZ = {
    'PAYME': {
        'PAYME_ID': env.str('PAYME_ID'),
        'PAYME_KEY': env.str('PAYME_KEY'),
        'ACCOUNT_MODEL': 'apps.payment.models.Wallet',
        'ACCOUNT_FIELD': 'id',
        'AMOUNT_FIELD': 'balance',
        'ONE_TIME_PAYMENT': False,
        'IS_TEST_MODE': env.bool('PAYME_IS_TEST_MODE', False),
    },
    'CLICK': {
        'SERVICE_ID': env.str('CLICK_SERVICE_ID'),
        'MERCHANT_ID': env.str('CLICK_MERCHANT_ID'),
        'MERCHANT_USER_ID': env.str('CLICK_MERCHANT_USER_ID'),
        'SECRET_KEY': env.str('CLICK_SECRET_KEY'),
        'ACCOUNT_MODEL': 'apps.payment.models.Wallet',
        'ACCOUNT_FIELD': 'id',
        'AMOUNT_FIELD': 'balance',
        'ONE_TIME_PAYMENT': False,
        'IS_TEST_MODE': env.bool('CLICK_IS_TEST_MODE', False),
    },
    'UZUM': {
        'SERVICE_ID': env.str('UZUM_SERVICE_ID'),
        'USERNAME': env.str('UZUM_USERNAME'),
        'PASSWORD': env.str('UZUM_PASSWORD'),
        'ACCOUNT_MODEL': 'apps.payment.models.Wallet',
        'ACCOUNT_FIELD': 'id',
        'AMOUNT_FIELD': 'balance',
        'IS_TEST_MODE': env.bool('UZUM_IS_TEST_MODE', False),
        'ONE_TIME_PAYMENT': False,
    },
    'PAYNET': {
        'SERVICE_ID': env.str('PAYNET_SERVICE_ID'),
        'USERNAME': env.str('PAYNET_USERNAME'),
        'PASSWORD': env.str('PAYNET_PASSWORD'),
        'ACCOUNT_MODEL': 'apps.payment.models.Wallet',
        'ACCOUNT_FIELD': 'id',
        'AMOUNT_FIELD': 'balance',
        'IS_TEST_MODE': env.bool('PAYNET_IS_TEST_MODE', False),
        'ONE_TIME_PAYMENT': False,
    }
}

CORS_ALLOW_ALL_ORIGINS = True

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "http://127.0.0.1:3000",
# ]

CORS_ALLOW_CREDENTIALS = True
